<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Hoofdstuk 2 Belangrijke concepten &amp; conventies | Cursus Statistiek 2019-2020</title>
  <meta name="description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Hoofdstuk 2 Belangrijke concepten &amp; conventies | Cursus Statistiek 2019-2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie" />
  <meta name="github-repo" content="statOmics/statistiek2deBach" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Hoofdstuk 2 Belangrijke concepten &amp; conventies | Cursus Statistiek 2019-2020" />
  
  <meta name="twitter:description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie" />
  

<meta name="author" content="Lieven Clement" />


<meta name="date" content="2019-09-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inleiding.html">
<link rel="next" href="chap-design.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Cursus Statistiek 2019-2020</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Woord vooraf</a></li>
<li class="chapter" data-level="" data-path="links.html"><a href="links.html"><i class="fa fa-check"></i>Links</a></li>
<li class="chapter" data-level="1" data-path="inleiding.html"><a href="inleiding.html"><i class="fa fa-check"></i><b>1</b> Inleiding</a><ul>
<li class="chapter" data-level="1.1" data-path="inleiding.html"><a href="inleiding.html#sec:wetMeth"><i class="fa fa-check"></i><b>1.1</b> De Wetenschappelijke Methode</a></li>
<li class="chapter" data-level="1.2" data-path="inleiding.html"><a href="inleiding.html#voorbeeld-horizon---homeopathy-the-test"><i class="fa fa-check"></i><b>1.2</b> Voorbeeld: Horizon - Homeopathy the test</a><ul>
<li class="chapter" data-level="1.2.1" data-path="inleiding.html"><a href="inleiding.html#wetenschappelijke-hypothese-fragmenten-1-2-000-600-740-1130"><i class="fa fa-check"></i><b>1.2.1</b> Wetenschappelijke hypothese (fragmenten 1-2: 0’00’‘-6’00’‘&amp; 7’40’‘-11’30’’)</a></li>
<li class="chapter" data-level="1.2.2" data-path="inleiding.html"><a href="inleiding.html#onderzoek-dient-reproduceerbaar-te-zijn.-wat-ging-er-fout-fragment-1450-1856"><i class="fa fa-check"></i><b>1.2.2</b> Onderzoek dient reproduceerbaar te zijn. Wat ging er fout? (Fragment: 14’50”-18’56”)</a></li>
<li class="chapter" data-level="1.2.3" data-path="inleiding.html"><a href="inleiding.html#the-ultimate-test---proefopzet-fragment-3100-3930"><i class="fa fa-check"></i><b>1.2.3</b> The ultimate test - proefopzet (Fragment 31’00-39’30’’)</a></li>
<li class="chapter" data-level="1.2.4" data-path="inleiding.html"><a href="inleiding.html#the-ultimate-test---data-analyse-fragment-3930-4300"><i class="fa fa-check"></i><b>1.2.4</b> The ultimate test - data analyse (Fragment 39’30-43’00’’)</a></li>
<li class="chapter" data-level="1.2.5" data-path="inleiding.html"><a href="inleiding.html#mogelijke-fouten"><i class="fa fa-check"></i><b>1.2.5</b> Mogelijke fouten</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html"><i class="fa fa-check"></i><b>2</b> Belangrijke concepten &amp; conventies</a><ul>
<li class="chapter" data-level="2.1" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#variabelen"><i class="fa fa-check"></i><b>2.1</b> Variabelen</a></li>
<li class="chapter" data-level="2.2" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#subsec:pop"><i class="fa fa-check"></i><b>2.2</b> Populatie</a></li>
<li class="chapter" data-level="2.3" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#toevalsveranderlijken-of-toevallige-veranderlijken"><i class="fa fa-check"></i><b>2.3</b> Toevalsveranderlijken (of toevallige veranderlijken)</a></li>
<li class="chapter" data-level="2.4" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#beschrijven-van-de-populatie"><i class="fa fa-check"></i><b>2.4</b> Beschrijven van de populatie</a></li>
<li class="chapter" data-level="2.5" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#steekproef"><i class="fa fa-check"></i><b>2.5</b> Steekproef</a></li>
<li class="chapter" data-level="2.6" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#schatten-van-de-verdeling-in-de-populatie"><i class="fa fa-check"></i><b>2.6</b> Schatten van de verdeling in de populatie</a></li>
<li class="chapter" data-level="2.7" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#statistieken"><i class="fa fa-check"></i><b>2.7</b> Statistieken</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-design.html"><a href="chap-design.html"><i class="fa fa-check"></i><b>3</b> Studiedesign</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-design.html"><a href="chap-design.html#inleiding-1"><i class="fa fa-check"></i><b>3.1</b> Inleiding</a></li>
<li class="chapter" data-level="3.2" data-path="chap-design.html"><a href="chap-design.html#sec:steekproefdesigns"><i class="fa fa-check"></i><b>3.2</b> Steekproefdesigns</a><ul>
<li class="chapter" data-level="3.2.1" data-path="chap-design.html"><a href="chap-design.html#replicatie"><i class="fa fa-check"></i><b>3.2.1</b> Replicatie</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chap-design.html"><a href="chap-design.html#experimentele-studies"><i class="fa fa-check"></i><b>3.3</b> Experimentele studies</a><ul>
<li class="chapter" data-level="3.3.1" data-path="chap-design.html"><a href="chap-design.html#de-salk-vaccin-veldstudie"><i class="fa fa-check"></i><b>3.3.1</b> De Salk Vaccin Veldstudie</a></li>
<li class="chapter" data-level="3.3.2" data-path="chap-design.html"><a href="chap-design.html#gerandomiseerd-gecontroleerde-studies"><i class="fa fa-check"></i><b>3.3.2</b> Gerandomiseerd gecontroleerde studies</a></li>
<li class="chapter" data-level="3.3.3" data-path="chap-design.html"><a href="chap-design.html#parallelle-designs"><i class="fa fa-check"></i><b>3.3.3</b> Parallelle designs</a></li>
<li class="chapter" data-level="3.3.4" data-path="chap-design.html"><a href="chap-design.html#cross-over-designs"><i class="fa fa-check"></i><b>3.3.4</b> Cross-over designs</a></li>
<li class="chapter" data-level="3.3.5" data-path="chap-design.html"><a href="chap-design.html#factoriele-designs"><i class="fa fa-check"></i><b>3.3.5</b> Factoriële designs</a></li>
<li class="chapter" data-level="3.3.6" data-path="chap-design.html"><a href="chap-design.html#quasi-experimentele-designs"><i class="fa fa-check"></i><b>3.3.6</b> Quasi-experimentele designs</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chap-design.html"><a href="chap-design.html#sec:observational"><i class="fa fa-check"></i><b>3.4</b> Observationele studies</a></li>
<li class="chapter" data-level="3.5" data-path="chap-design.html"><a href="chap-design.html#subsec:design:prosp"><i class="fa fa-check"></i><b>3.5</b> Prospectieve studies</a></li>
<li class="chapter" data-level="3.6" data-path="chap-design.html"><a href="chap-design.html#subsec:design:retro"><i class="fa fa-check"></i><b>3.6</b> Retrospectieve studies</a></li>
<li class="chapter" data-level="3.7" data-path="chap-design.html"><a href="chap-design.html#niet-gecontroleerde-studies"><i class="fa fa-check"></i><b>3.7</b> Niet-gecontroleerde studies</a><ul>
<li class="chapter" data-level="3.7.1" data-path="chap-design.html"><a href="chap-design.html#subsec:prepost"><i class="fa fa-check"></i><b>3.7.1</b> Pre-test/Post-test studies</a></li>
<li class="chapter" data-level="3.7.2" data-path="chap-design.html"><a href="chap-design.html#cross-sectionele-surveys"><i class="fa fa-check"></i><b>3.7.2</b> Cross-sectionele surveys</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-describe.html"><a href="chap-describe.html"><i class="fa fa-check"></i><b>4</b> Data exploratie en beschrijvende statistiek</a><ul>
<li class="chapter" data-level="4.1" data-path="chap-describe.html"><a href="chap-describe.html#inleiding-2"><i class="fa fa-check"></i><b>4.1</b> Inleiding</a></li>
<li class="chapter" data-level="4.2" data-path="chap-describe.html"><a href="chap-describe.html#sec:univar"><i class="fa fa-check"></i><b>4.2</b> Univariate beschrijving van de variabelen</a></li>
<li class="chapter" data-level="4.3" data-path="chap-describe.html"><a href="chap-describe.html#sec:summarize"><i class="fa fa-check"></i><b>4.3</b> Samenvattingsmaten voor continue variabelen</a><ul>
<li class="chapter" data-level="4.3.1" data-path="chap-describe.html"><a href="chap-describe.html#maten-voor-de-centrale-ligging"><i class="fa fa-check"></i><b>4.3.1</b> Maten voor de centrale ligging</a></li>
<li class="chapter" data-level="4.3.2" data-path="chap-describe.html"><a href="chap-describe.html#subsec:spreiding"><i class="fa fa-check"></i><b>4.3.2</b> Spreidingsmaten</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-describe.html"><a href="chap-describe.html#sec:normal"><i class="fa fa-check"></i><b>4.4</b> De Normale benadering van gegevens</a><ul>
<li class="chapter" data-level="4.4.1" data-path="chap-describe.html"><a href="chap-describe.html#subsec:normalcalc"><i class="fa fa-check"></i><b>4.4.1</b> Bepalen van oppervlaktes onder de Normale curve</a></li>
<li class="chapter" data-level="4.4.2" data-path="chap-describe.html"><a href="chap-describe.html#sec:qq"><i class="fa fa-check"></i><b>4.4.2</b> QQ-plots</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-describe.html"><a href="chap-describe.html#sec:explCatVar"><i class="fa fa-check"></i><b>4.5</b> Samenvattingsmaten voor categorische variabelen</a><ul>
<li class="chapter" data-level="4.5.1" data-path="chap-describe.html"><a href="chap-describe.html#prospectieve-studies-en-lukrake-steekproeven"><i class="fa fa-check"></i><b>4.5.1</b> Prospectieve studies en lukrake steekproeven</a></li>
<li class="chapter" data-level="4.5.2" data-path="chap-describe.html"><a href="chap-describe.html#subsec:retrospect"><i class="fa fa-check"></i><b>4.5.2</b> Retrospectieve studies</a></li>
<li class="chapter" data-level="4.5.3" data-path="chap-describe.html"><a href="chap-describe.html#rates-versus-risicos"><i class="fa fa-check"></i><b>4.5.3</b> Rates versus risico’s</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="chap-describe.html"><a href="chap-describe.html#associaties-tussen-twee-variabelen"><i class="fa fa-check"></i><b>4.6</b> Associaties tussen twee variabelen</a><ul>
<li class="chapter" data-level="4.6.1" data-path="chap-describe.html"><a href="chap-describe.html#subsec:kruistabel"><i class="fa fa-check"></i><b>4.6.1</b> Associatie tussen twee kwalitatieve variabelen</a></li>
<li class="chapter" data-level="4.6.2" data-path="chap-describe.html"><a href="chap-describe.html#subsec:asskwalcont"><i class="fa fa-check"></i><b>4.6.2</b> Associatie tussen één kwalitatieve en één continue variabele</a></li>
<li class="chapter" data-level="4.6.3" data-path="chap-describe.html"><a href="chap-describe.html#sec:correlatie"><i class="fa fa-check"></i><b>4.6.3</b> Associatie tussen twee continue variabelen</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="chap-describe.html"><a href="chap-describe.html#sec:missing"><i class="fa fa-check"></i><b>4.7</b> Onvolledige gegevens</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-besluit.html"><a href="chap-besluit.html"><i class="fa fa-check"></i><b>5</b> Statistische besluitvorming</a><ul>
<li class="chapter" data-level="5.1" data-path="chap-besluit.html"><a href="chap-besluit.html#inleiding-3"><i class="fa fa-check"></i><b>5.1</b> Inleiding</a></li>
<li class="chapter" data-level="5.2" data-path="chap-besluit.html"><a href="chap-besluit.html#captopril-voorbeeld"><i class="fa fa-check"></i><b>5.2</b> Captopril voorbeeld</a><ul>
<li class="chapter" data-level="5.2.1" data-path="chap-besluit.html"><a href="chap-besluit.html#proefopzet"><i class="fa fa-check"></i><b>5.2.1</b> Proefopzet</a></li>
<li class="chapter" data-level="5.2.2" data-path="chap-besluit.html"><a href="chap-besluit.html#data-exploratie-beschrijvende-statistiek"><i class="fa fa-check"></i><b>5.2.2</b> Data Exploratie &amp; Beschrijvende Statistiek</a></li>
<li class="chapter" data-level="5.2.3" data-path="chap-besluit.html"><a href="chap-besluit.html#schatten"><i class="fa fa-check"></i><b>5.2.3</b> Schatten</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chap-besluit.html"><a href="chap-besluit.html#puntschatters-het-steekproefgemiddelde"><i class="fa fa-check"></i><b>5.3</b> Puntschatters: het steekproefgemiddelde</a><ul>
<li class="chapter" data-level="5.3.1" data-path="chap-besluit.html"><a href="chap-besluit.html#het-steekproefgemiddelde-is-onvertekend"><i class="fa fa-check"></i><b>5.3.1</b> Het steekproefgemiddelde is onvertekend</a></li>
<li class="chapter" data-level="5.3.2" data-path="chap-besluit.html"><a href="chap-besluit.html#imprecisiestandard-error"><i class="fa fa-check"></i><b>5.3.2</b> Imprecisie/standard error</a></li>
<li class="chapter" data-level="5.3.3" data-path="chap-besluit.html"><a href="chap-besluit.html#subsec:verdelingXbar"><i class="fa fa-check"></i><b>5.3.3</b> Verdeling van het steekproefgemiddelde</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="chap-besluit.html"><a href="chap-besluit.html#intervalschatters"><i class="fa fa-check"></i><b>5.4</b> Intervalschatters</a><ul>
<li class="chapter" data-level="5.4.1" data-path="chap-besluit.html"><a href="chap-besluit.html#subsec:bigek"><i class="fa fa-check"></i><b>5.4.1</b> Gekende variantie op de metingen</a></li>
<li class="chapter" data-level="5.4.2" data-path="chap-besluit.html"><a href="chap-besluit.html#sec:tBI"><i class="fa fa-check"></i><b>5.4.2</b> Ongekende variantie op de metingen</a></li>
<li class="chapter" data-level="5.4.3" data-path="chap-besluit.html"><a href="chap-besluit.html#subsec:interpretBI"><i class="fa fa-check"></i><b>5.4.3</b> Interpretatie van betrouwbaarheidsintervallen</a></li>
<li class="chapter" data-level="5.4.4" data-path="chap-besluit.html"><a href="chap-besluit.html#wat-rapporteren"><i class="fa fa-check"></i><b>5.4.4</b> Wat rapporteren?</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="chap-besluit.html"><a href="chap-besluit.html#principe-van-hypothesetoetsen-via-one-sample-t-test"><i class="fa fa-check"></i><b>5.5</b> Principe van Hypothesetoetsen (via one sample t-test)</a><ul>
<li class="chapter" data-level="5.5.1" data-path="chap-besluit.html"><a href="chap-besluit.html#hypotheses"><i class="fa fa-check"></i><b>5.5.1</b> Hypotheses</a></li>
<li class="chapter" data-level="5.5.2" data-path="chap-besluit.html"><a href="chap-besluit.html#test-statistiek"><i class="fa fa-check"></i><b>5.5.2</b> Test-statistiek</a></li>
<li class="chapter" data-level="5.5.3" data-path="chap-besluit.html"><a href="chap-besluit.html#de-p-waarde"><i class="fa fa-check"></i><b>5.5.3</b> De p-waarde</a></li>
<li class="chapter" data-level="5.5.4" data-path="chap-besluit.html"><a href="chap-besluit.html#kritieke-waarde"><i class="fa fa-check"></i><b>5.5.4</b> Kritieke waarde</a></li>
<li class="chapter" data-level="5.5.5" data-path="chap-besluit.html"><a href="chap-besluit.html#beslissingsfouten"><i class="fa fa-check"></i><b>5.5.5</b> Beslissingsfouten</a></li>
<li class="chapter" data-level="5.5.6" data-path="chap-besluit.html"><a href="chap-besluit.html#conclusies-captopril-voorbeeld."><i class="fa fa-check"></i><b>5.5.6</b> Conclusies Captopril voorbeeld.</a></li>
<li class="chapter" data-level="5.5.7" data-path="chap-besluit.html"><a href="chap-besluit.html#eenzijdig-of-tweezijdig-toetsen"><i class="fa fa-check"></i><b>5.5.7</b> Eenzijdig of tweezijdig toetsen?</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="chap-besluit.html"><a href="chap-besluit.html#two-sample-t-test"><i class="fa fa-check"></i><b>5.6</b> Two-sample t-test</a><ul>
<li class="chapter" data-level="5.6.1" data-path="chap-besluit.html"><a href="chap-besluit.html#oksel-voorbeeld"><i class="fa fa-check"></i><b>5.6.1</b> Oksel-voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chap-besluit.html"><a href="chap-besluit.html#aannames"><i class="fa fa-check"></i><b>5.7</b> Aannames</a><ul>
<li class="chapter" data-level="5.7.1" data-path="chap-besluit.html"><a href="chap-besluit.html#nagaan-van-de-veronderstelling-van-normaliteit"><i class="fa fa-check"></i><b>5.7.1</b> Nagaan van de veronderstelling van Normaliteit</a></li>
<li class="chapter" data-level="5.7.2" data-path="chap-besluit.html"><a href="chap-besluit.html#nagaan-van-homoscedasticiteit"><i class="fa fa-check"></i><b>5.7.2</b> Nagaan van homoscedasticiteit</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="chap-besluit.html"><a href="chap-besluit.html#wat-rapporteren-1"><i class="fa fa-check"></i><b>5.8</b> Wat rapporteren?</a><ul>
<li class="chapter" data-level="5.8.1" data-path="chap-besluit.html"><a href="chap-besluit.html#reden-1-relatie-toetsen-en-betrouwbaarheidsintervallen"><i class="fa fa-check"></i><b>5.8.1</b> Reden 1: Relatie toetsen en betrouwbaarheidsintervallen</a></li>
<li class="chapter" data-level="5.8.2" data-path="chap-besluit.html"><a href="chap-besluit.html#reden-2-statistische-significantie-versus-wetenschappelijke-relevantie"><i class="fa fa-check"></i><b>5.8.2</b> Reden 2: Statistische significantie versus wetenschappelijke relevantie</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="chap-besluit.html"><a href="chap-besluit.html#equivalentie-intervallen"><i class="fa fa-check"></i><b>5.9</b> Equivalentie-intervallen</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-linReg.html"><a href="chap-linReg.html"><i class="fa fa-check"></i><b>6</b> Enkelvoudige lineaire regressie</a><ul>
<li class="chapter" data-level="6.1" data-path="chap-linReg.html"><a href="chap-linReg.html#inleiding-4"><i class="fa fa-check"></i><b>6.1</b> Inleiding</a><ul>
<li class="chapter" data-level="6.1.1" data-path="chap-linReg.html"><a href="chap-linReg.html#borstkanker-dataset"><i class="fa fa-check"></i><b>6.1.1</b> Borstkanker dataset</a></li>
<li class="chapter" data-level="6.1.2" data-path="chap-linReg.html"><a href="chap-linReg.html#data-exploratie"><i class="fa fa-check"></i><b>6.1.2</b> Data exploratie</a></li>
<li class="chapter" data-level="6.1.3" data-path="chap-linReg.html"><a href="chap-linReg.html#model"><i class="fa fa-check"></i><b>6.1.3</b> Model</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="chap-linReg.html"><a href="chap-linReg.html#lineaire-regressie"><i class="fa fa-check"></i><b>6.2</b> Lineaire regressie</a></li>
<li class="chapter" data-level="6.3" data-path="chap-linReg.html"><a href="chap-linReg.html#parameterschatting"><i class="fa fa-check"></i><b>6.3</b> Parameterschatting</a></li>
<li class="chapter" data-level="6.4" data-path="chap-linReg.html"><a href="chap-linReg.html#sec:linBesluit"><i class="fa fa-check"></i><b>6.4</b> Statistische besluitvorming</a></li>
<li class="chapter" data-level="6.5" data-path="chap-linReg.html"><a href="chap-linReg.html#nagaan-van-modelveronderstellingen"><i class="fa fa-check"></i><b>6.5</b> Nagaan van modelveronderstellingen</a><ul>
<li class="chapter" data-level="6.5.1" data-path="chap-linReg.html"><a href="chap-linReg.html#lineariteit"><i class="fa fa-check"></i><b>6.5.1</b> Lineariteit</a></li>
<li class="chapter" data-level="6.5.2" data-path="chap-linReg.html"><a href="chap-linReg.html#veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie"><i class="fa fa-check"></i><b>6.5.2</b> Veronderstelling van homoscedasticiteit (gelijkheid van variantie)</a></li>
<li class="chapter" data-level="6.5.3" data-path="chap-linReg.html"><a href="chap-linReg.html#veronderstelling-van-normaliteit"><i class="fa fa-check"></i><b>6.5.3</b> Veronderstelling van normaliteit</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="chap-linReg.html"><a href="chap-linReg.html#afwijkingen-van-modelveronderstellingen"><i class="fa fa-check"></i><b>6.6</b> Afwijkingen van Modelveronderstellingen</a></li>
<li class="chapter" data-level="6.7" data-path="chap-linReg.html"><a href="chap-linReg.html#besluitvorming-over-gemiddelde-uitkomst"><i class="fa fa-check"></i><b>6.7</b> Besluitvorming over gemiddelde uitkomst</a></li>
<li class="chapter" data-level="6.8" data-path="chap-linReg.html"><a href="chap-linReg.html#predictie-intervallen"><i class="fa fa-check"></i><b>6.8</b> Predictie-intervallen</a></li>
<li class="chapter" data-level="6.9" data-path="chap-linReg.html"><a href="chap-linReg.html#sec:linAnova"><i class="fa fa-check"></i><b>6.9</b> Kwadratensommen en Anova-tabel</a><ul>
<li class="chapter" data-level="6.9.1" data-path="chap-linReg.html"><a href="chap-linReg.html#determinatie-coefficient"><i class="fa fa-check"></i><b>6.9.1</b> Determinatie-coëfficiënt</a></li>
<li class="chapter" data-level="6.9.2" data-path="chap-linReg.html"><a href="chap-linReg.html#f-testen-in-het-enkelvoudig-lineair-regressiemodel"><i class="fa fa-check"></i><b>6.9.2</b> F-Testen in het enkelvoudig lineair regressiemodel</a></li>
<li class="chapter" data-level="6.9.3" data-path="chap-linReg.html"><a href="chap-linReg.html#anova-tabel"><i class="fa fa-check"></i><b>6.9.3</b> Anova Tabel</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="chap-linReg.html"><a href="chap-linReg.html#sec:linDummy"><i class="fa fa-check"></i><b>6.10</b> Dummy variabelen</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-anova.html"><a href="chap-anova.html"><i class="fa fa-check"></i><b>7</b> Variantie analyse</a><ul>
<li class="chapter" data-level="7.1" data-path="chap-anova.html"><a href="chap-anova.html#inleiding-5"><i class="fa fa-check"></i><b>7.1</b> Inleiding</a><ul>
<li class="chapter" data-level="7.1.1" data-path="chap-anova.html"><a href="chap-anova.html#prostacycline-voorbeeld"><i class="fa fa-check"></i><b>7.1.1</b> Prostacycline voorbeeld</a></li>
<li class="chapter" data-level="7.1.2" data-path="chap-anova.html"><a href="chap-anova.html#model-1"><i class="fa fa-check"></i><b>7.1.2</b> Model</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="chap-anova.html"><a href="chap-anova.html#variantie-analyse"><i class="fa fa-check"></i><b>7.2</b> Variantie-analyse</a><ul>
<li class="chapter" data-level="7.2.1" data-path="chap-anova.html"><a href="chap-anova.html#model-2"><i class="fa fa-check"></i><b>7.2.1</b> Model</a></li>
<li class="chapter" data-level="7.2.2" data-path="chap-anova.html"><a href="chap-anova.html#kwadratensommen-en-anova"><i class="fa fa-check"></i><b>7.2.2</b> Kwadratensommen en Anova</a></li>
<li class="chapter" data-level="7.2.3" data-path="chap-anova.html"><a href="chap-anova.html#anova-test"><i class="fa fa-check"></i><b>7.2.3</b> Anova-test</a></li>
<li class="chapter" data-level="7.2.4" data-path="chap-anova.html"><a href="chap-anova.html#anova-tabel-1"><i class="fa fa-check"></i><b>7.2.4</b> Anova Tabel</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="chap-anova.html"><a href="chap-anova.html#post-hoc-analyse-meervoudig-vergelijken-van-gemiddelden"><i class="fa fa-check"></i><b>7.3</b> Post hoc analyse: Meervoudig Vergelijken van Gemiddelden</a><ul>
<li class="chapter" data-level="7.3.1" data-path="chap-anova.html"><a href="chap-anova.html#naieve-methode"><i class="fa fa-check"></i><b>7.3.1</b> Naïeve methode</a></li>
<li class="chapter" data-level="7.3.2" data-path="chap-anova.html"><a href="chap-anova.html#family-wise-error-rate"><i class="fa fa-check"></i><b>7.3.2</b> Family-wise error rate</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="chap-anova.html"><a href="chap-anova.html#conclusies-prostacycline-voorbeeld"><i class="fa fa-check"></i><b>7.4</b> Conclusies: Prostacycline Voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html"><i class="fa fa-check"></i><b>8</b> Niet-parametrische statistiek</a><ul>
<li class="chapter" data-level="8.1" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#inleiding-6"><i class="fa fa-check"></i><b>8.1</b> Inleiding</a></li>
<li class="chapter" data-level="8.2" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#vergelijken-van-twee-groepen"><i class="fa fa-check"></i><b>8.2</b> Vergelijken van twee groepen</a><ul>
<li class="chapter" data-level="8.2.1" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#cholestorol-voorbeeld"><i class="fa fa-check"></i><b>8.2.1</b> Cholestorol voorbeeld</a></li>
<li class="chapter" data-level="8.2.2" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#permutatietesten"><i class="fa fa-check"></i><b>8.2.2</b> Permutatietesten</a></li>
<li class="chapter" data-level="8.2.3" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#rank-testen"><i class="fa fa-check"></i><b>8.2.3</b> Rank Testen</a></li>
<li class="chapter" data-level="8.2.4" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#wilcoxon-mann-whitney-test"><i class="fa fa-check"></i><b>8.2.4</b> Wilcoxon-Mann-Whitney Test</a></li>
<li class="chapter" data-level="8.2.5" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#conclusie-cholestorol-voorbeeld"><i class="fa fa-check"></i><b>8.2.5</b> Conclusie Cholestorol Voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#vergelijken-van-g-behandelingen"><i class="fa fa-check"></i><b>8.3</b> Vergelijken van <span class="math inline">\(g\)</span> Behandelingen</a><ul>
<li class="chapter" data-level="8.3.1" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#dmh-voorbeeld"><i class="fa fa-check"></i><b>8.3.1</b> DMH Voorbeeld</a></li>
<li class="chapter" data-level="8.3.2" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#permutatietest"><i class="fa fa-check"></i><b>8.3.2</b> Permutatietest</a></li>
<li class="chapter" data-level="8.3.3" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#kruskal-wallis-rank-test"><i class="fa fa-check"></i><b>8.3.3</b> Kruskal-Wallis Rank Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-categorisch.html"><a href="chap-categorisch.html"><i class="fa fa-check"></i><b>9</b> Categorische data analyse</a><ul>
<li class="chapter" data-level="9.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#inleiding-7"><i class="fa fa-check"></i><b>9.1</b> Inleiding</a></li>
<li class="chapter" data-level="9.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#toetsen-voor-een-proportie"><i class="fa fa-check"></i><b>9.2</b> Toetsen voor een proportie</a><ul>
<li class="chapter" data-level="9.2.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#subsec:binom"><i class="fa fa-check"></i><b>9.2.1</b> Binomiale test</a></li>
<li class="chapter" data-level="9.2.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#betrouwbaarheidsinterval-op-een-proportie"><i class="fa fa-check"></i><b>9.2.2</b> Betrouwbaarheidsinterval op een proportie</a></li>
<li class="chapter" data-level="9.2.3" data-path="chap-categorisch.html"><a href="chap-categorisch.html#conclusie"><i class="fa fa-check"></i><b>9.2.3</b> Conclusie</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="chap-categorisch.html"><a href="chap-categorisch.html#toets-voor-associatie-tussen-2-kwalitatieve-variabelen"><i class="fa fa-check"></i><b>9.3</b> Toets voor associatie tussen 2 kwalitatieve variabelen</a><ul>
<li class="chapter" data-level="9.3.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#gepaarde-gegevens"><i class="fa fa-check"></i><b>9.3.1</b> Gepaarde gegevens</a></li>
<li class="chapter" data-level="9.3.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#subsec:catOnPaired"><i class="fa fa-check"></i><b>9.3.2</b> Ongepaarde gegevens</a></li>
<li class="chapter" data-level="9.3.3" data-path="chap-categorisch.html"><a href="chap-categorisch.html#de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens"><i class="fa fa-check"></i><b>9.3.3</b> De Pearson Chi-kwadraat test voor ongepaarde gegevens</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="chap-categorisch.html"><a href="chap-categorisch.html#logistische-regressie"><i class="fa fa-check"></i><b>9.4</b> Logistische regressie</a><ul>
<li class="chapter" data-level="9.4.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#categorische-predictor"><i class="fa fa-check"></i><b>9.4.1</b> Categorische predictor</a></li>
<li class="chapter" data-level="9.4.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#continue-predictor"><i class="fa fa-check"></i><b>9.4.2</b> Continue predictor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-glm.html"><a href="chap-glm.html"><i class="fa fa-check"></i><b>10</b> Algemeen lineair model</a><ul>
<li class="chapter" data-level="10.1" data-path="chap-glm.html"><a href="chap-glm.html#inleiding-8"><i class="fa fa-check"></i><b>10.1</b> Inleiding</a><ul>
<li class="chapter" data-level="10.1.1" data-path="chap-glm.html"><a href="chap-glm.html#sec:prostate"><i class="fa fa-check"></i><b>10.1.1</b> Prostaatkanker dataset</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="chap-glm.html"><a href="chap-glm.html#het-additieve-meervoudig-lineaire-regressie-model"><i class="fa fa-check"></i><b>10.2</b> Het additieve meervoudig lineaire regressie model</a><ul>
<li class="chapter" data-level="10.2.1" data-path="chap-glm.html"><a href="chap-glm.html#statistisch-model"><i class="fa fa-check"></i><b>10.2.1</b> Statistisch model</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="chap-glm.html"><a href="chap-glm.html#besluitvorming-in-regressiemodellen"><i class="fa fa-check"></i><b>10.3</b> Besluitvorming in regressiemodellen</a></li>
<li class="chapter" data-level="10.4" data-path="chap-glm.html"><a href="chap-glm.html#nagaan-van-modelveronderstellingen-1"><i class="fa fa-check"></i><b>10.4</b> Nagaan van modelveronderstellingen</a><ul>
<li class="chapter" data-level="10.4.1" data-path="chap-glm.html"><a href="chap-glm.html#lineariteit-1"><i class="fa fa-check"></i><b>10.4.1</b> Lineariteit</a></li>
<li class="chapter" data-level="10.4.2" data-path="chap-glm.html"><a href="chap-glm.html#homoscedasticiteit"><i class="fa fa-check"></i><b>10.4.2</b> Homoscedasticiteit</a></li>
<li class="chapter" data-level="10.4.3" data-path="chap-glm.html"><a href="chap-glm.html#normaliteit"><i class="fa fa-check"></i><b>10.4.3</b> Normaliteit</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="chap-glm.html"><a href="chap-glm.html#het-niet-additieve-meervoudig-lineair-regressiemodel"><i class="fa fa-check"></i><b>10.5</b> Het niet-additieve meervoudig lineair regressiemodel</a><ul>
<li class="chapter" data-level="10.5.1" data-path="chap-glm.html"><a href="chap-glm.html#sec:intCont"><i class="fa fa-check"></i><b>10.5.1</b> Interactie tussen twee continue variabelen</a></li>
<li class="chapter" data-level="10.5.2" data-path="chap-glm.html"><a href="chap-glm.html#interactie-tussen-continue-variabele-en-factor-variabele"><i class="fa fa-check"></i><b>10.5.2</b> Interactie tussen continue variabele en factor variabele</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="chap-glm.html"><a href="chap-glm.html#anova-tabel-2"><i class="fa fa-check"></i><b>10.6</b> ANOVA Tabel</a><ul>
<li class="chapter" data-level="10.6.1" data-path="chap-glm.html"><a href="chap-glm.html#sstot-ssr-en-sse"><i class="fa fa-check"></i><b>10.6.1</b> SSTot, SSR en SSE</a></li>
<li class="chapter" data-level="10.6.2" data-path="chap-glm.html"><a href="chap-glm.html#extra-kwadratensommen"><i class="fa fa-check"></i><b>10.6.2</b> Extra Kwadratensommen</a></li>
<li class="chapter" data-level="10.6.3" data-path="chap-glm.html"><a href="chap-glm.html#type-i-kwadratensommen"><i class="fa fa-check"></i><b>10.6.3</b> Type I Kwadratensommen</a></li>
<li class="chapter" data-level="10.6.4" data-path="chap-glm.html"><a href="chap-glm.html#type-iii-kwadratensommen"><i class="fa fa-check"></i><b>10.6.4</b> Type III Kwadratensommen</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="chap-glm.html"><a href="chap-glm.html#regressiediagnostieken"><i class="fa fa-check"></i><b>10.7</b> Regressiediagnostieken</a><ul>
<li class="chapter" data-level="10.7.1" data-path="chap-glm.html"><a href="chap-glm.html#multicollineariteit"><i class="fa fa-check"></i><b>10.7.1</b> Multicollineariteit</a></li>
<li class="chapter" data-level="10.7.2" data-path="chap-glm.html"><a href="chap-glm.html#invloedrijke-observaties"><i class="fa fa-check"></i><b>10.7.2</b> Invloedrijke observaties</a></li>
<li class="chapter" data-level="10.7.3" data-path="chap-glm.html"><a href="chap-glm.html#cooks-distance"><i class="fa fa-check"></i><b>10.7.3</b> Cook’s distance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap-modsel.html"><a href="chap-modsel.html"><i class="fa fa-check"></i><b>11</b> Modelselectie</a><ul>
<li class="chapter" data-level="11.1" data-path="chap-modsel.html"><a href="chap-modsel.html#inleiding-9"><i class="fa fa-check"></i><b>11.1</b> Inleiding</a></li>
<li class="chapter" data-level="11.2" data-path="chap-modsel.html"><a href="chap-modsel.html#modelselectie-op-basis-van-hypothesetesten"><i class="fa fa-check"></i><b>11.2</b> Modelselectie op basis van hypothesetesten</a><ul>
<li class="chapter" data-level="11.2.1" data-path="chap-modsel.html"><a href="chap-modsel.html#voorwaartse-modelselectie"><i class="fa fa-check"></i><b>11.2.1</b> Voorwaartse modelselectie</a></li>
<li class="chapter" data-level="11.2.2" data-path="chap-modsel.html"><a href="chap-modsel.html#achterwaartse-modelselectie"><i class="fa fa-check"></i><b>11.2.2</b> Achterwaartse modelselectie</a></li>
<li class="chapter" data-level="11.2.3" data-path="chap-modsel.html"><a href="chap-modsel.html#stapsgewijze-modelselectie"><i class="fa fa-check"></i><b>11.2.3</b> Stapsgewijze modelselectie</a></li>
<li class="chapter" data-level="11.2.4" data-path="chap-modsel.html"><a href="chap-modsel.html#opmerkingen"><i class="fa fa-check"></i><b>11.2.4</b> Opmerkingen</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="chap-modsel.html"><a href="chap-modsel.html#modelselectie-voor-predictie"><i class="fa fa-check"></i><b>11.3</b> Modelselectie voor predictie</a><ul>
<li class="chapter" data-level="11.3.1" data-path="chap-modsel.html"><a href="chap-modsel.html#inleiding-10"><i class="fa fa-check"></i><b>11.3.1</b> Inleiding</a></li>
<li class="chapter" data-level="11.3.2" data-path="chap-modsel.html"><a href="chap-modsel.html#selectie-criterium"><i class="fa fa-check"></i><b>11.3.2</b> Selectie-criterium</a></li>
<li class="chapter" data-level="11.3.3" data-path="chap-modsel.html"><a href="chap-modsel.html#alternatieve-criteria"><i class="fa fa-check"></i><b>11.3.3</b> Alternatieve criteria</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Cursus Statistiek 2019-2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="belangrijke-concepten-conventies" class="section level1">
<h1><span class="header-section-number">Hoofdstuk 2</span> Belangrijke concepten &amp; conventies</h1>
<p>De verschillende stappen in een studie worden geïllustreerd in Figuur <a href="belangrijke-concepten-conventies.html#fig:pop2Samp2Pop">2.1</a>. Eerst bepaalt de onderzoeker de <em>populatie</em> van interesse. Gezien het om financiële en logistieke beperkingen vrijwel nooit mogelijk is om de volledige populatie te onderzoeken zal men vervolgens een steekproef nemen uit de populatie. De manier waarop een steekproef zal worden genomen wordt vastgelegd in het <em>design van de studie</em>. <em>Proefopzet</em> of <em>studie design</em> is een aparte tak van de statisitiek en is een cruciaal onderdeel van een studie. Het studie design moet immers garanderen dat de gegevens en resultaten van de steekproef representatief zijn voor de populatie zodat de resultaten van de studie veralgemeneend kunnen worden naar de populatie toe. Vervolgens wordt de studie uitgevoerd, worden de gegevens verzameld en kan de eigenlijke data-analyse van start gaan. In een eerste fase is het belangrijk om de gegevens grondig te exploreren. <em>Data-exploratie en beschrijvende statistiek</em> is een tweede tak van de statistiek die toelaat om gegevens van de steekproef te visualiseren, samen te vatten en om inzicht in de data te verwerven. Dat is belangrijk om de data correct te kunnen modelleren en om aannames na te kunnen gaan die nodig zijn voor de verdere data analyse. Vervolgens zullen we hetgeen we observeren in de steekproef trachten te veralgemenen naar de algemene populatie toe, zodat we algemene conclusies kunnen trekken op populatie-niveau op basis van de steekproef van de studie. Hiervoor zijn methodes nodig van de <em>statistische besluitvorming</em>, ook wel <em>statistische inferentie</em> genoemd, een derde belangrijke tak van de statistiek.</p>
<div class="figure" style="text-align: center"><span id="fig:pop2Samp2Pop"></span>
<img src="Statistiek_2019_2020_files/figure-html/pop2Samp2Pop-1.png" alt="Verschillende stappen in een studie. (1) In de design fase/ proefopzet definieert de onderzoeker de populatie, bepaalt hij/zij op welke manier een steekproef zal worden genomen uit de populatie en hoe het experiment zal worden uitgevoerd. Ook het volledige data analyse plan moet in deze fase zijn vastgelegd. Vervolgens wordt het experiment uitgevoerd en worden de gegevens verzameld. (2) De gegevens worden vervolgens verkend en samengevat. Hierbij verwerft men inzicht in de gegevens en kunnen aannames worden nagegaan die noodzakelijk zijn voor de verdere data analyse stappen. (3) Tenslotte zal men hetgeen men observeert in de steekproef trachten te veralgemenen naar de populatie toe a.d.h.v. statistische inferentie." width="100%" />
<p class="caption">
Figuur 2.1: Verschillende stappen in een studie. (1) In de design fase/ proefopzet definieert de onderzoeker de populatie, bepaalt hij/zij op welke manier een steekproef zal worden genomen uit de populatie en hoe het experiment zal worden uitgevoerd. Ook het volledige data analyse plan moet in deze fase zijn vastgelegd. Vervolgens wordt het experiment uitgevoerd en worden de gegevens verzameld. (2) De gegevens worden vervolgens verkend en samengevat. Hierbij verwerft men inzicht in de gegevens en kunnen aannames worden nagegaan die noodzakelijk zijn voor de verdere data analyse stappen. (3) Tenslotte zal men hetgeen men observeert in de steekproef trachten te veralgemenen naar de populatie toe a.d.h.v. statistische inferentie.
</p>
</div>
<p>Vooraleer we dieper ingaan op studie-design, data-exploratie en statistische besluitvorming zullen we eerst enkele concepten introduceren. We doen dat in dit hoofdstuk aan de hand van de de NHANES studie.</p>

<div class="example">
<span id="exm:nhanesExConcepten" class="example"><strong>Voorbeeld 2.1  (NHANES studie)  </strong></span>
</div>

<p>De National Health and Nutrition Examination Survey (NHANES) wordt sinds 1960 op regelmatige basis afgenomen. In dit voorbeeld maken we gebruik van de gegevens die werden verzameld tussen 2009-2012 bij 10000 Amerikanen en die werden opgenomen in het R-pakket NHANES. Er werd een groot aantal fysieke, demografische, nutritionele, levelsstijl en gezondheidskarakteristieken gecollecteerd in deze studie (zie Tabel <a href="belangrijke-concepten-conventies.html#tab:nhanesConcepten">2.1</a>). <code>**Einde voorbeeld**</code></p>
<table>
<caption>
<span id="tab:nhanesConcepten">Tabel 2.1: </span>Overzicht van een aantal variabelen uit de NHANES studie.
</caption>
<thead>
<tr>
<th style="text-align:right;">
ID
</th>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
Age
</th>
<th style="text-align:left;">
Race1
</th>
<th style="text-align:right;">
Weight
</th>
<th style="text-align:right;">
Height
</th>
<th style="text-align:right;">
BMI
</th>
<th style="text-align:right;">
BPSysAve
</th>
<th style="text-align:right;">
TotChol
</th>
<th style="text-align:left;">
SmokeNow
</th>
<th style="text-align:left;">
Smoke100
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
51624
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
87.4
</td>
<td style="text-align:right;">
164.7
</td>
<td style="text-align:right;">
32.22
</td>
<td style="text-align:right;">
113
</td>
<td style="text-align:right;">
3.49
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:left;">
Yes
</td>
</tr>
<tr>
<td style="text-align:right;">
51625
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Other
</td>
<td style="text-align:right;">
17.0
</td>
<td style="text-align:right;">
105.4
</td>
<td style="text-align:right;">
15.30
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
51630
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
86.7
</td>
<td style="text-align:right;">
168.4
</td>
<td style="text-align:right;">
30.57
</td>
<td style="text-align:right;">
112
</td>
<td style="text-align:right;">
6.70
</td>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:left;">
Yes
</td>
</tr>
<tr>
<td style="text-align:right;">
51638
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
29.8
</td>
<td style="text-align:right;">
133.1
</td>
<td style="text-align:right;">
16.82
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
4.86
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
51646
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
35.2
</td>
<td style="text-align:right;">
130.6
</td>
<td style="text-align:right;">
20.64
</td>
<td style="text-align:right;">
107
</td>
<td style="text-align:right;">
4.09
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
51647
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
75.7
</td>
<td style="text-align:right;">
166.7
</td>
<td style="text-align:right;">
27.24
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
5.82
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
No
</td>
</tr>
</tbody>
</table>
<div id="variabelen" class="section level2">
<h2><span class="header-section-number">2.1</span> Variabelen</h2>
<p>Een <em>variabele</em> is een karakteristiek (bvb. Systolische bloeddruk, leeftijd, geslacht, …) die varieert van subject tot subject (bvb. van persoon tot persoon, van dier tot dier, …) in de studie. Er zijn verschillende <em>types</em> variabelen.</p>
<p><em>Kwalitatieve variabelen</em> hebben (meestal) beperkt aantal uitkomstcategorieën die niet numeriek van aard zijn. Deze worden onderverdeeld in <em>nominale variabelen</em> en <em>ordinale variabelen</em> . Nominale gegevens zijn er die men kan benoemen. Ze worden niet gemeten en kennen geen natuurlijke ordening; bijvoorbeeld geslacht, ras, bloedgroep, kleur van ogen, … Ordinale variabelen kennen wel een ordening; bijvoorbeeld de BMI klasse volgens het WHO, de rokersstatus (nooit gerookt, ooit gerookt maar gestopt, actueel roker), …</p>
<p>Een ander type van variabelen zijn <em>numerieke variabelen</em>. Hierbij maakt men het onderscheid tussen <em>numerieke discrete variabelen</em> en <em>numerieke continue variabelen</em>. Numerieke discrete variabelen bestaan uit tellingen, b.v. het aantal partners die men had gedurende het leven (geregistreerd in de NHANES studie), het aantal salamanders van de species <strong>P. jordani</strong> in een bepaald gebied, het aantal reads dat mapt op een bepaald gen in een genexpressiestudie waarbij men gebruik maakt van next-generation sequencing technologie , …</p>
<p>Numerieke continue variabelen kunnen (tenminste in theorie) tussen bepaalde grenzen elke mogelijke waarde aannemen. Bijvoorbeeld, leeftijd is continu want het verschil in leeftijd tussen 2 personen kan in principe willekeurig klein zijn (1 uur, 1 minuut, …). Analoog zijn het gewicht, BMI, fluorescentie-metingen in een ELISA experiment, … continue metingen.</p>
<p>In de wetenschappen gaat men vaak continue gegevens dichotomiseren om ze nominaal te maken. Bijvoorbeeld, systolische bloeddruk wordt omgezet in hypertensie (<span class="math inline">\(&gt;140\)</span> mmHg) en normotensie (<span class="math inline">\(\leq 140\)</span> mmHg). Dit vereenvoudigt de beschrijving van gegevens. Helaas is dit een slechte praktijk omdat het meestal leidt tot een aanzienlijk verlies aan informatie en omdat de aldus bekomen resultaten sterk afhankelijk kunnen zijn van de gekozen drempelwaarde. In de praktijk worden de uitkomsten van continue variabelen ook vaak afgerond zodat de vermelde waarden in feite discreet zijn. Om analoge redenen is het vaak wenselijk om ze als continue variabelen te blijven beschouwen.</p>
<p>In de praktijk wil men vaak numerieke rangen toekennen aan de verschillende waarden die ordinale variabelen aannemen. Bijvoorbeeld kan men ervoor kiezen de codes 1, 2 en 3 toe te kennen aan de meetwaarden <em>nooit gerookt</em>, <em>ooit gerookt maar gestopt</em> en <em>actueel roker</em>. Het is belangrijk om te beseffen dat de keuze van die numerieke waarden vaak geen betekenis heeft. Het verschil tussen de toegekende codes (3-2=1, 2-1=1, 3-2=1) is niet bruikbaar gezien men bijvoorbeeld niet onderstellen dat de wijziging in rokerstatus identiek is van <em>nooit gerookt</em> naar <em>ooit gerookt maar gestopt</em> (2-1=1) en van <em>ooit gerookt maar gestopt</em> naar <em>actueel roker</em> (3-2=1).</p>

<div class="example">
<span id="exm:unnamed-chunk-3" class="example"><strong>Voorbeeld 2.2  (oefening)  </strong></span>Geef het type aan van de variabelen in Tabel <a href="belangrijke-concepten-conventies.html#tab:nhanesConcepten">2.1</a>
</div>

</div>
<div id="subsec:pop" class="section level2">
<h2><span class="header-section-number">2.2</span> Populatie</h2>
<p>Het doel van een wetenschappelijke studie is nagenoeg altijd om uitspraken te doen over de algemene populatie. Stel bijvoorbeeld dat men een grenswaarde wil afleiden om patiënten met hypertensie op te sporen. Hiervoor zal men eerst de systolische bloeddruk moeten bestuderen bij een populatie van gezonde personen. Een populatie is meestal continu in verandering. Bovendien is men meestal niet alleen geïnteresseerd in effecten bij huidige subjecten, maar ook in het effect bij toekomstige subjecten. De populatie kan dus als oneindig groot worden beschouwd en is op een bepaald ogenblik zelfs niet volledig observeerbaar<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a>. De populatie kan binnen de statistiek dus worden opgevat als een theoretisch concept die alle huidige en toekomstige subjecten omvat waarover men uitspraken wenst te doen. In de praktijk zal men dus nooit de volledige populatie kunnen bemonsteren en dient men een steekproef te nemen van de populatie. Om een representatieve groep subjecten te waarborgen, vertrekt een goede onderzoeksopzet vanuit een belangrijke, precies geformuleerde vraagstelling omtrent een duidelijk omschreven populatie. Vaak worden hierbij inclusie- en exclusiecriteria geformuleerd.</p>
<p><em>Inclusiecriteria</em> zijn karakteristieken die een subject/experimentele eenheid moet hebben om tot de populatie te behoren, b.v.</p>
<ul>
<li>specifieke ziekte: hypertensie</li>
<li>leeftijdscategorie</li>
<li>geslacht</li>
<li>…</li>
</ul>
<p><em>Exclusiecriteria</em> zijn karakteristieken die een subject/experimentele eenheid niet mag hebben om tot de populatie te behoren, b.v.</p>
<ul>
<li>geneesmiddelen gebruik</li>
<li>andere ziekten</li>
<li>zwangerschap</li>
<li>…</li>
</ul>
<p>Op de subjecten zal men meestal een aantal karakteristieken meten, ook wel <em>variabelen</em> genoemd (bvb. Systolische bloeddruk, leeftijd, geslacht, …). Typisch zullen deze variabelen variëren van subject tot subject (bvb. van persoon tot persoon, van dier tot dier, …) in de populatie.</p>
</div>
<div id="toevalsveranderlijken-of-toevallige-veranderlijken" class="section level2">
<h2><span class="header-section-number">2.3</span> Toevalsveranderlijken (of toevallige veranderlijken)</h2>
<p>De belangrijke vraag, waar we in in de verdere hoofdstukken dieper op in zullen gaan, is hoe nauwkeurig we uitspraken kunnen doen over de populatie o.b.v. een groep gemeten subjecten in een steekproef. De spreiding op de gegevens zal daar een cruciale rol in spelen. Als de gegevens niet variëren tussen subjecten, dan zullen alle steekproeven uit de populatie hetzelfde resultaat opleveren en zullen de bekomen schattingen niet afwijken van de gezochte populatieparameters. Als daarentegen de gegevens zeer chaotisch zijn, dan zullen verschillende steekproeven mogelijks zeer verschillende resultaten opleveren, die bijgevolg ver kunnen afwijken van de gezochte populatieparameters.</p>
<p>Om het denkwerk te vergemakkelijken, zullen we hoofdletters gebruiken om aan te geven dat de bestudeerde karakteristiek (vb. een meetresultaat zoals systolische bloeddruk) variabel is in de populatie, zonder daarbij concreet over de gerealiseerde waarde voor een bepaald subject na te denken. Dergelijke meting of variabele <span class="math inline">\(X\)</span> wordt algemeen een <em>toevalsveranderlijke</em> of <em>toevallige veranderlijke</em> genoemd, (a) omdat ze formeel het resultaat aanduidt van een <em>toevallige trekking</em> van een bepaalde karakteristiek uit de studiepopulatie en (b) omdat ze bovendien <em>veranderlijk</em> is, niet alle subjecten in de steekproef bezitten immers dezelfde waarde voor die karakteristiek.</p>
<p>Het makkelijkst om over een toevalsveranderlijke <span class="math inline">\(X\)</span> na te denken is alsof <span class="math inline">\(X\)</span> het label voorstelt van een bepaalde populatiekarakteristiek voor een lukraak individu uit de bestudeerde populatie, vooraleer haar concrete waarde gemeten werd. Met andere woorden, een toevalsveranderlijke <span class="math inline">\(X\)</span> kan men opvatten als onbekende veranderlijke die een meting voorstelt die we plannen te verzamelen, maar nog niet hebben verzameld. Net zoals observaties kunnen we toevallig veranderlijken klasseren als kwalitatief, kwantitatief, discreet, continu, ….</p>
</div>
<div id="beschrijven-van-de-populatie" class="section level2">
<h2><span class="header-section-number">2.4</span> Beschrijven van de populatie</h2>
<p>Voor we een random variabele meten, kunnen we onmogelijk zeggen hoe hoog de meting precies zal zijn. De gerealiseerde waarde van <span class="math inline">\(X\)</span> is dus onderhevig aan random variabiliteit. Onze geobserveerde steekproef <span class="math inline">\(x_1, x_2, . . . , x_{275}\)</span> kan dus als n = 275 realisaties worden beschouwd van dezelfde random variable X, voor subject <span class="math inline">\(i\)</span>, met <span class="math inline">\(i = 1,2,...,275\)</span>. Een random veranderlijke, een karakteristiek van de populatie, wordt beschreven door gebruik te maken van een <em>verdeling</em>.</p>
<p>De verdeling beschrijft de waarschijnlijkheid om een bepaalde waarde te observeren voor de toevallig veranderlijke wanneer men volledige lukraak een proefpersoon kiest uit de populatie. De densiteitsfunctie van de verdeling wordt vaak genoteerd als f(X). Heel vaak volgen biologische en chemische data een Normale verdeling. De Normale verdeling is een theoretische verdeling met een klokvorm die volledig gedefineerd wordt door twee parameters, het gemiddelde <span class="math inline">\(\mu\)</span> en de variantie <span class="math inline">\(\sigma^2\)</span>. We zullen in latere hoofdstukken dieper ingaan op de normale verdeling.</p>
<p>Veronderstel bijvoorbeeld dat de gemiddelde bloeddruk van subjecten in de populatie van gezonde 40-65 jarigen gelijk is aan <span class="math inline">\(\mu=120\)</span> mmHg en de variantie <span class="math inline">\(\sigma^2=196\)</span>. De verdeling van de systolische bloeddruk wordt weergegeven in Figuur <a href="belangrijke-concepten-conventies.html#fig:nhanesNormal">2.2</a> die d.m.v. onderstaande code wordt gegenereerd in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">grid &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">65</span>,<span class="dv">175</span>,.<span class="dv">1</span>)
<span class="kw">plot</span>(grid,<span class="kw">dnorm</span>(grid,<span class="dt">mean=</span><span class="dv">120</span>,<span class="dt">sd=</span><span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>),<span class="dt">xlab=</span><span class="st">&quot;Systolische Bloeddruk (mm kwik)&quot;</span>,<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">ylab=</span><span class="st">&quot;Densiteit&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)
grid2&lt;-<span class="kw">seq</span>(<span class="dv">115</span>,<span class="dv">120</span>,.<span class="dv">01</span>)
<span class="kw">polygon</span>(<span class="dt">x=</span><span class="kw">c</span>(grid2,<span class="dv">120</span>,<span class="dv">115</span>),<span class="dt">y=</span><span class="kw">c</span>(<span class="kw">dnorm</span>(grid2,<span class="dv">120</span>,<span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>),<span class="dv">0</span>,<span class="dv">0</span>),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">border=</span><span class="dv">2</span>)
<span class="kw">text</span>(<span class="dv">120</span>,<span class="kw">dnorm</span>(<span class="dv">120</span>,<span class="dv">120</span>,<span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>),<span class="kw">paste0</span>(<span class="st">&quot;P(115 &lt; X &lt; 120) =&quot;</span>,<span class="kw">round</span>( <span class="kw">diff</span>(<span class="kw">pnorm</span>(<span class="kw">c</span>(<span class="dv">115</span>,<span class="dv">120</span>),<span class="dv">120</span>,<span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>)) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">1</span>),<span class="st">&quot;%&quot;</span>),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">cex=</span><span class="dv">1</span>,<span class="dt">pos=</span><span class="dv">4</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:nhanesNormal"></span>
<img src="Statistiek_2019_2020_files/figure-html/nhanesNormal-1.png" alt="Normale verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar met gemiddelde 120 mm Hg en variantie 196." width="100%" />
<p class="caption">
Figuur 2.2: Normale verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar met gemiddelde 120 mm Hg en variantie 196.
</p>
</div>
<p>Op basis van de verdeling kunnen we kansen berekenen om bijvoorbeeld een lukraak subject te bemonsteren uit de populatie met een bloeddruk tussen 115 en 120 mmHg. De kansen worden weergegeven door de oppervlakte onder de densiteitsfunctie:</p>
<p><span class="math display">\[P[115\leq  X\leq 120]= \int\limits_{115}^{120} f(x) dx = 0.14\]</span></p>
<p>De grafische interpretatie wordt weergegeven in Figuur <a href="belangrijke-concepten-conventies.html#fig:nhanesNormal">2.2</a>. De oppervlakte onder de volledige densiteitscurve is gelijk aan 1</p>
<p><span class="math display">\[P[-\infty\leq X \leq +\infty]=\int\limits_{-\infty}^{+\infty} f(x) dx=1\]</span></p>
<p>Kansen liggen uiteraard steeds tussen 0 en 1!</p>
<p>Kansen worden veelal berekend door gebruik te maken van de <em>cumulatieve distributie functie</em> van de verdeling, F(x), m.a.w. de functie die weergeeft wat de kans is dat een Normaal verdeelde toevallige veranderlijke een waarde zal aannemen die kleiner of gelijk is aan de vooropgestelde kwantiel x: <span class="math display">\[F(x)=\int\limits_{-\infty}^x f(x) dx  = P[X\leq x].\]</span></p>
<p><img src="Statistiek_2019_2020_files/figure-html/nhanesNormalCum-1.png" width="60%" style="display: block; margin: auto;" /><img src="Statistiek_2019_2020_files/figure-html/nhanesNormalCum-2.png" width="60%" style="display: block; margin: auto;" /> Merk op dat de de normale distributie in R wordt geparameteriseerd a.d.h.v. het gemiddelde <span class="math inline">\(\mu\)</span> en de standaard afwijking <span class="math inline">\(\sigma\)</span>. Op basis van de Normaal verdeling die we veronderstelden voor de systolische bloeddruk in de populatie <span class="math inline">\(N(\mu=120\)</span>,<span class="math inline">\(\sigma^2=196)\)</span> bekomen we</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">120</span>,<span class="dt">mean=</span><span class="dv">120</span>,<span class="dt">sd=</span><span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">115</span>,<span class="dt">mean=</span><span class="dv">120</span>,<span class="dt">sd=</span><span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 0.3604924</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">120</span>,<span class="dt">mean=</span><span class="dv">120</span>,<span class="dt">sd=</span><span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>)<span class="op">-</span><span class="kw">pnorm</span>(<span class="dv">115</span>,<span class="dt">mean=</span><span class="dv">120</span>,<span class="dt">sd=</span><span class="dv">196</span><span class="op">^</span>.<span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 0.1395076</code></pre>
<p>waarbij pnorm de kans berekent dat de bloeddruk bij een willekeurig subject in de populatie lager of gelijk is aan het kwantiel dat wordt opgegeven (hier 120 mm Hg en 115 mm Hg). Het verschil tussen beide kansen geeft dan de kans weer op een bloeddruk tussen 115 en 120 mm Hg. Let wel dat R de parameterisatie gebruikt van het gemiddelde <span class="math inline">\(\mu\)</span> en de standaard afwijking <span class="math inline">\(\sigma\)</span>, ipv de variantie <span class="math inline">\(\sigma^2\)</span>.</p>
<p>In de praktijk kennen we de werkelijke verdeling in de populatie niet en moet deze worden geschat o.b.v. de steekproef.</p>
</div>
<div id="steekproef" class="section level2">
<h2><span class="header-section-number">2.5</span> Steekproef</h2>
<p>In de praktijk is het om financiële en logistieke redenen bijna nooit mogelijk om de volledige populatie te bestuderen. Populatieparameters kunnen daarom meestal niet exact bepaald worden. Enkel een deel van de populatie kan onderzocht worden, hetgeen men de <em>steekproef</em> noemt. Volgens een gestructureerd design worden daartoe <strong>lukraak subjecten</strong> uit de doelpopulatie getrokken en geobserveerd. De onbekende parameters worden vervolgens geschat o.b.v. die steekproef en noemt met schattingen. In de praktijk hoopt men uiteraard dat de schattingen die men bekomt op basis van de steekproef vergelijkbaar zijn met de overeenkomstige populatieparameters die men voor de volledige populatie zou bekomen.</p>
<p>Stel bijvoorbeeld dat we op basis van de NHANES studie hypertensie wensen te definiëren. We zullen hiervoor subjecten met “normale” bloeddrukwaarden moeten selecteren. Veronderstel dat we <span class="math inline">\(n\)</span> gezonde personen zullen selecteren in de studie tussen 40 en 65 jaar en we geïnteresseerd zijn in systolische bloeddruk. Telkens een lukraak individu getrokken wordt uit de populatie zal men een realisatie van de toevalsveranderlijke <span class="math inline">\(X\)</span> kunnen observeren. Die realisatie of geobserveerde waarde duiden we aan met een kleine letter <span class="math inline">\(x\)</span>. Deze stelt dus een welbepaald getal voor en is niet langer een onbekende veranderlijke zoals <span class="math inline">\(X\)</span>. Samengevat zijn de nog onbekende waarden voor de bestudeerde populatiekarakteristiek bij subjecten 1 tot <span class="math inline">\(n\)</span> in de steekproef, toevalsveranderlijken die we algemeen met <span class="math inline">\(X_1,...,X_n\)</span> zullen noteren. Na het trekken van de steekproef, ziet men de gerealiseerde uitkomsten <span class="math inline">\(x_1, x_2, \dots, x_n\)</span>, bijvoorbeeld hun gemeten systolische bloeddruk.</p>
<p>We selecteren hieronder de subset van gezonde personen tussen de 40-65 jaar in de NHANES studie. Deze definiëren we verder als niet rokers, zonder diabetes, met een normaal BMI, zonder historiek van hard drugs, zonder lage gezondheidsstatus en zonder slaapproblemen. Op deze manier hebben we dus inclusie- en exclusiecriteria geformuleerd voor het definiëren van de populatie van interesse.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(NHANES)
NHANES2=<span class="kw">subset</span>(NHANES,<span class="op">!</span><span class="kw">is.na</span>(Race1)<span class="op">&amp;!</span><span class="kw">is.na</span>(Smoke100n)<span class="op">&amp;!</span><span class="kw">is.na</span>(BMI_WHO)<span class="op">%in%!</span><span class="kw">is.na</span>(Age)<span class="op">&amp;!</span><span class="kw">is.na</span>(HardDrugs)<span class="op">&amp;!</span><span class="kw">is.na</span>(HealthGen)<span class="op">&amp;!</span><span class="kw">is.na</span>(Gender)<span class="op">&amp;!</span><span class="kw">is.na</span>(AlcoholYear)<span class="op">&amp;!</span><span class="kw">is.na</span>(BPSys1)<span class="op">&amp;!</span><span class="kw">is.na</span>(BPSys2)<span class="op">&amp;!</span><span class="kw">is.na</span>(BPSys3)<span class="op">&amp;!</span><span class="kw">is.na</span>(SleepTrouble))
NHANES2<span class="op">$</span>bpSys=<span class="kw">rowMeans</span>(NHANES2[,<span class="kw">c</span>(<span class="dv">27</span>,<span class="dv">29</span>,<span class="dv">31</span>)])
nhanesSub=<span class="kw">subset</span>(NHANES2, Age<span class="op">&lt;=</span><span class="dv">65</span><span class="op">&amp;</span>Age<span class="op">&gt;=</span><span class="dv">40</span> <span class="op">&amp;!</span><span class="kw">duplicated</span>(ID) )
nhanesSubHealthy=<span class="kw">subset</span>(nhanesSub,Smoke100n<span class="op">==</span><span class="st">&quot;Non-Smoker&quot;</span><span class="op">&amp;</span>Diabetes<span class="op">==</span><span class="st">&quot;No&quot;</span><span class="op">&amp;</span><span class="kw">as.double</span>(BMI_WHO)<span class="op">%in%</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)<span class="op">&amp;</span>HardDrugs<span class="op">==</span><span class="st">&quot;No&quot;</span><span class="op">&amp;</span>HealthGen<span class="op">!=</span><span class="st">&quot;Poor&quot;</span><span class="op">&amp;</span>SleepTrouble<span class="op">==</span><span class="st">&quot;No&quot;</span>)
<span class="kw">head</span>(nhanesSubHealthy<span class="op">$</span>bpSys)</code></pre></div>
<pre><code>## [1] 114.00000 140.66667  94.66667 152.66667 128.00000 124.00000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(nhanesSubHealthy)</code></pre></div>
<pre><code>## [1] 275  77</code></pre>
<p>Op basis van de inclusie en exclusie-criteria werden <span class="math inline">\(n=275\)</span> gezonde individuen uit de Amerikaanse populatie weerhouden. De toevallig veranderlijke systolische bloeddruk wordt dus genoteerd als <span class="math inline">\(X\)</span> terwijl de n = 275 geobserveerde metingen genoteerd worden als <span class="math inline">\(x_1,x_2,...,x_{275}\)</span>. De variable <span class="math inline">\(X\)</span> is random of stochastisch aangezien zijn waarde veranderlijk is. Voor een random subject uit de populatie kunnen we de systolische bloeddruk niet exact voorspellen, het hangt immers af van het geselecteerde subject, tijdstip van de meting, …</p>
</div>
<div id="schatten-van-de-verdeling-in-de-populatie" class="section level2">
<h2><span class="header-section-number">2.6</span> Schatten van de verdeling in de populatie</h2>
<p>In realiteit kennen we de verdeling van de gegevens niet. We kunnen de verdeling o.b.v. de steekproef schatten en grafisch weergegeven a.d.h.v. een histogram (functie <code>hist()</code> in R)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">histAbs&lt;-<span class="kw">hist</span>(nhanesSubHealthy<span class="op">$</span>bpSys,<span class="dt">xlab=</span><span class="st">&quot;Systolische Bloeddruk (mm kwik).&quot;</span>,<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">65</span>,<span class="dv">175</span>,<span class="dv">5</span>),<span class="dt">ylab=</span><span class="st">&quot;Frequentie&quot;</span>,<span class="dt">cex.main=</span><span class="fl">1.5</span>,<span class="dt">cex.axis=</span><span class="fl">1.5</span>,<span class="dt">cex.lab=</span><span class="fl">1.5</span>,<span class="dt">main=</span><span class="st">&quot;&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:nhanesNormalSteekproef"></span>
<img src="Statistiek_2019_2020_files/figure-html/nhanesNormalSteekproef-1.png" alt="Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie. (Absolute frequenties)" width="100%" />
<p class="caption">
Figuur 2.3: Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie. (Absolute frequenties)
</p>
</div>
<p>Merk op dat de hoogte van de balken, aantallen op de y-as, weergeeft hoeveel subjecten vallen in een bepaald interval bloeddrukken ([80-85[, [85-90[, …). Op basis van de steekproef kunnen we via het histogram schatten wat de kans is om een random persoon te bemonsteren met een bloeddruk tussen 115 - 120 mm Hg uit de populatie .</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab&lt;-<span class="kw">cbind</span>(histAbs<span class="op">$</span>mids,histAbs<span class="op">$</span>counts)
tab</code></pre></div>
<pre><code>##        [,1] [,2]
##  [1,]  67.5    0
##  [2,]  72.5    0
##  [3,]  77.5    0
##  [4,]  82.5    1
##  [5,]  87.5    2
##  [6,]  92.5    6
##  [7,]  97.5    9
##  [8,] 102.5   22
##  [9,] 107.5   35
## [10,] 112.5   33
## [11,] 117.5   41
## [12,] 122.5   36
## [13,] 127.5   35
## [14,] 132.5   17
## [15,] 137.5   13
## [16,] 142.5   12
## [17,] 147.5    8
## [18,] 152.5    3
## [19,] 157.5    1
## [20,] 162.5    0
## [21,] 167.5    0
## [22,] 172.5    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab[tab[,<span class="dv">1</span>]<span class="op">==</span><span class="fl">117.5</span>,<span class="dv">2</span>]<span class="op">/</span><span class="kw">sum</span>(tab[,<span class="dv">2</span>])</code></pre></div>
<pre><code>## [1] 0.1490909</code></pre>
<p>Op basis van de steekproef wordt die kans geschat op 14.9%.</p>
<p>Een histogram kan ook weergegeven worden a.d.h.v. relatieve frequenties/densiteiten.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(nhanesSubHealthy<span class="op">$</span>bpSys,<span class="dt">xlab=</span><span class="st">&quot;Systolische Bloeddruk (mm kwik).&quot;</span>,<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">65</span>,<span class="dv">175</span>,<span class="dv">5</span>),<span class="dt">freq=</span><span class="ot">FALSE</span>,<span class="dt">ylab=</span><span class="st">&quot;Densiteit&quot;</span>,<span class="dt">cex.main=</span><span class="fl">1.5</span>,<span class="dt">cex.axis=</span><span class="fl">1.5</span>,<span class="dt">cex.lab=</span><span class="fl">1.5</span>,<span class="dt">main=</span><span class="st">&quot;&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:nhanesNormalSteekproefRel"></span>
<img src="Statistiek_2019_2020_files/figure-html/nhanesNormalSteekproefRel-1.png" alt="Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie. (Relatieve frequenties)" width="100%" />
<p class="caption">
Figuur 2.4: Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie. (Relatieve frequenties)
</p>
</div>
<p>De oppervlakte in elke balk komt dan overeen met een kans: hoogte van de balk x breedte van de balk. In de histogrammen hebben we voor de breedte van de balk 5 mm Hg gekozen.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab2&lt;-<span class="kw">cbind</span>(histAbs<span class="op">$</span>mids,histAbs<span class="op">$</span>density)
tab2</code></pre></div>
<pre><code>##        [,1]         [,2]
##  [1,]  67.5 0.0000000000
##  [2,]  72.5 0.0000000000
##  [3,]  77.5 0.0000000000
##  [4,]  82.5 0.0007272727
##  [5,]  87.5 0.0014545455
##  [6,]  92.5 0.0043636364
##  [7,]  97.5 0.0065454545
##  [8,] 102.5 0.0160000000
##  [9,] 107.5 0.0254545455
## [10,] 112.5 0.0240000000
## [11,] 117.5 0.0298181818
## [12,] 122.5 0.0261818182
## [13,] 127.5 0.0254545455
## [14,] 132.5 0.0123636364
## [15,] 137.5 0.0094545455
## [16,] 142.5 0.0087272727
## [17,] 147.5 0.0058181818
## [18,] 152.5 0.0021818182
## [19,] 157.5 0.0007272727
## [20,] 162.5 0.0000000000
## [21,] 167.5 0.0000000000
## [22,] 172.5 0.0007272727</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab2[tab2[,<span class="dv">1</span>]<span class="op">==</span><span class="fl">117.5</span>,<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] 0.02981818</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab2[tab2[,<span class="dv">1</span>]<span class="op">==</span><span class="fl">117.5</span>,<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span><span class="dv">5</span></code></pre></div>
<pre><code>## [1] 0.1490909</code></pre>
<p>We bekomen opnieuw een schatting van 14.9%. We geven dat weer in een figuur, waarbij we de functie <code>rect()</code> gebruiken om de rechthoekige balk te tekenen. A.d.h.v. de functie <code>text()</code> kunnen we ook tekst toevoegen aan de figuur.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(nhanesSubHealthy<span class="op">$</span>bpSys,<span class="dt">xlab=</span><span class="st">&quot;Systolische Bloeddruk (mm kwik).&quot;</span>,<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">65</span>,<span class="dv">175</span>,<span class="dv">5</span>),<span class="dt">freq=</span><span class="ot">FALSE</span>,<span class="dt">ylab=</span><span class="st">&quot;Densiteit&quot;</span>,<span class="dt">cex.main=</span><span class="fl">1.5</span>,<span class="dt">cex.axis=</span><span class="fl">1.5</span>,<span class="dt">cex.lab=</span><span class="fl">1.5</span>,<span class="dt">main=</span><span class="st">&quot;&quot;</span>)
<span class="kw">rect</span>(<span class="dv">115</span>,<span class="dv">0</span>,<span class="dv">120</span>, tab2[tab2[,<span class="dv">1</span>]<span class="op">==</span><span class="fl">117.5</span>,<span class="dv">2</span>],<span class="dt">col=</span><span class="dv">2</span>)
<span class="kw">text</span>(<span class="dv">120</span>,tab2[tab2[,<span class="dv">1</span>]<span class="op">==</span><span class="fl">117.5</span>,<span class="dv">2</span>],<span class="kw">paste0</span>(<span class="st">&quot;P(115 &lt; X &lt; 120) = &quot;</span>,<span class="kw">round</span>(tab2[tab2[,<span class="dv">1</span>]<span class="op">==</span><span class="fl">117.5</span>,<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span><span class="dv">5</span> <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">1</span>),<span class="st">&quot;%&quot;</span>),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">cex=</span><span class="dv">1</span>,<span class="dt">pos=</span><span class="dv">4</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:nhanesNormalSteekproefRelProb"></span>
<img src="Statistiek_2019_2020_files/figure-html/nhanesNormalSteekproefRelProb-1.png" alt="Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie. (Het histogram wordt weergegeven a.d.h.v. relatieve frequenties en de geschatte kans op een bloeddruk tussen 115-120 wordt aangeduid in het rood)" width="100%" />
<p class="caption">
Figuur 2.5: Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie. (Het histogram wordt weergegeven a.d.h.v. relatieve frequenties en de geschatte kans op een bloeddruk tussen 115-120 wordt aangeduid in het rood)
</p>
</div>
<p>Als we de som van de oppervlakte van alle balken zouden berekenen is die uiteraard gelijk aan 1. De kans om een random persoon uit de steekproef aan te treffen tussen de laagste en hoogste waarde in de steekproef dient immers gelijk te zijn aan 1 of 100%!</p>
<p>Het histogram geeft verder weer dat de verdeling inderdaad vrij symmetrisch blijkt te zijn en een klokvorm lijkt te hebben. Als we kunnen veronderstellen dat de gegevens normaal verdeeld zijn dan kunnen we de verdeling in de populatie ook schatten door enkel het gemiddelde <span class="math inline">\(\mu\)</span> en de variantie <span class="math inline">\(\sigma^2\)</span> te <em>schatten</em> en de parameterschattingen in te pluggen in de Normale verdeling.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(nhanesSubHealthy<span class="op">$</span>bpSys,<span class="dt">xlab=</span><span class="st">&quot;Systolische Bloeddruk (mm kwik).&quot;</span>,<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">65</span>,<span class="dv">175</span>,<span class="dv">5</span>),<span class="dt">freq=</span><span class="ot">FALSE</span>,<span class="dt">ylab=</span><span class="st">&quot;Densiteit&quot;</span>,<span class="dt">cex.main=</span><span class="fl">1.5</span>,<span class="dt">cex.axis=</span><span class="fl">1.5</span>,<span class="dt">cex.lab=</span><span class="fl">1.5</span>,<span class="dt">main=</span><span class="st">&quot;&quot;</span>)
<span class="kw">lines</span>(grid,<span class="kw">dnorm</span>(grid,<span class="dt">mean=</span><span class="kw">mean</span>(nhanesSubHealthy<span class="op">$</span>bpSys),<span class="dt">sd=</span><span class="kw">sd</span>(nhanesSubHealthy<span class="op">$</span>bpSys)),<span class="dt">xlab=</span><span class="st">&quot;Systolische Bloeddruk (mm kwik)&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Densiteit&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:nhanesNormalSteekproefEstimate"></span>
<img src="Statistiek_2019_2020_files/figure-html/nhanesNormalSteekproefEstimate-1.png" alt="Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie en a.d.h.v. een normale verdeling met geschat gemiddelde 120.4 mm Hg en geschatte variantie 129.8 (zwarte volle lijn)" width="100%" />
<p class="caption">
Figuur 2.6: Weergave van de verdeling voor de systolische bloeddruk van gezonde personen tussen 40-65 jaar geschat aan de hand van een histogram o.b.v. de geobserveerde steekproef in de NHANES studie en a.d.h.v. een normale verdeling met geschat gemiddelde 120.4 mm Hg en geschatte variantie 129.8 (zwarte volle lijn)
</p>
</div>
<p>In plaats van kansen te berekenen door gebruik te maken van het histogram, bestaat een alternatieve methode erin om het gemiddelde en de variantie te schatten op basis van de steekproef. Vervolgens wordt dan de kans berekend a.d.h.v. een normale verdeling waarbij we als gemiddelde en variantie de overeenkomstige schattingen in de steekproef gebruiken.</p>
<p>We illustreren dit in R. De normale verdeling in R wordt geparameteriseerd a.d.h.v. het gemiddelde <span class="math inline">\(\mu\)</span> en de standaard afwijking <span class="math inline">\(\sigma\)</span>. Deze laatste kan direct worden geschat a.d.h.v. de steekproef door gebruik te maken van de steekproef standaard deviatie (functie <code>sd()</code>). De kans die we dan bekomen is</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xBar &lt;-<span class="st"> </span><span class="kw">mean</span>(nhanesSubHealthy<span class="op">$</span>bpSys)
sBar &lt;-<span class="st"> </span><span class="kw">sd</span>(nhanesSubHealthy<span class="op">$</span>bpSys)
<span class="kw">pnorm</span>(<span class="dv">120</span>,<span class="dt">mean=</span>xBar,<span class="dt">sd=</span>sBar)<span class="op">-</span><span class="kw">pnorm</span>(<span class="dv">115</span>,<span class="dt">mean=</span>xBar,<span class="dt">sd=</span>sBar)</code></pre></div>
<pre><code>## [1] 0.1397006</code></pre>
<p>Merk op dat deze schatting veel dichter ligt bij de werkelijke kans in de populatie dan de schatting die we bekwamen d.m.v. het histogram. De schatting o.b.v. de normale verdeling is inderdaad nauwkeuriger: we kunnen immers gebruik maken van alle data om deze kans te schatten gezien we het steekproefgemiddelde en de steekproefstandaarddeviatie hebben geschat o.b.v. alle gegevens in de steekproef. Voor de kans berekend o.b.v. het histogram konden we daarentegen enkel de gegevens gebruiken van de personen uit de steekproef met een bloeddruk tussen 115 en 120 mmHg.<br />
Uiteraard zal het in de praktijk steeds heel belangrijk zijn om na te gaan of er voldaan is aan de aannames die we maken over de verdeling. Anders zijn onze schattingen immers incorrect en niet bruikbaar. Het nagaan van veronderstellingen over de verdeling is één van de doelstellingen van data exploratie.</p>
<p>We kunnen nu op basis van de steekproef en de aannames van normaliteit een grenswaarde voor de bloeddruk afleiden die extreem is voor “gezonde” personen in de populatie. Dat laat ons bijvoorbeeld toe om een bloeddruk te bepalen die maar met een kans van 5% wordt overschreden in de populatie van gezonde subjecten: <span class="math display">\[P(X &gt; t_\text{drempel}) = 5\%\]</span> of <span class="math display">\[P(X \leq t_\text{drempel}) = 95\%\]</span></p>
<p>Dat kan met de functie <code>qnorm()</code> in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(<span class="fl">0.95</span>,<span class="dt">mean=</span>xBar,<span class="dt">sd=</span>sBar)</code></pre></div>
<pre><code>## [1] 142.6011</code></pre>
<p>Deze waarde ligt dicht bij 140 mmg Hg, een grenswaarde voor hypertensie die vaak in de literatuur wordt gebruikt.</p>
</div>
<div id="statistieken" class="section level2">
<h2><span class="header-section-number">2.7</span> Statistieken</h2>
<p>Formules die gebruikt worden om parameters van de verdeling in de populatie te schatten op basis van de steekproef, alsook het numerieke resultaat dat men bekomt door deze formules te evalueren, worden <em>statistieken</em> genoemd. Bijvoorbeeld het rekenkundig gemiddelde van alle systolische bloeddrukwaarden voor de verschillende subjecten in de steekproef, is een statistiek. Statistieken zijn dus wat de onderzoekers observeren of kunnen berekenen o.b.v. de gegevens in de steekproef; parameters zijn wat ze eigenlijk willen weten. Omdat statistieken berekend worden op basis van de gegevens uit de steekproef, zullen ze variëren van steekproef tot steekproef. We zullen ze daarom noteren met een hoofdletter (bvb. <span class="math inline">\(\bar X\)</span> voor het steekproefgemiddelde), tenzij we verwijzen naar de numerieke waarde die gerealiseerd wordt in een bepaalde steekproef, in welk geval we een kleine letter gebruiken (bvb. <span class="math inline">\(\bar x\)</span> voor het steekproefgemiddelde).</p>
<p><strong>Belangrijke Conventie:</strong> In de cursus gebruiken we de conventie om <strong>populatieparameters die een vaste waarden aannemen maar die meestal ongekend zijn</strong> voor te stellen door <strong>Griekse symbolen</strong>. <strong>Statistieken</strong> waarmee we deze ongekende parameters schatten o.b.v. een steekproef zullen we weergeven door <strong>letters</strong>.</p>
<p>Voor de normaal verdeling hebben we dus:</p>
<table>
<thead>
<tr class="header">
<th align="center">Populatie</th>
<th align="center">Steekproef</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(\mu\)</span></td>
<td align="center"><span class="math inline">\(\bar X\)</span></td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\sigma^2\)</span></td>
<td align="center"><span class="math inline">\(S^2\)</span></td>
</tr>
</tbody>
</table>
<p>Om hetgeen we in de steekproef observeren te kunnen veralgemenen naar de populatie, zullen we gebruik moeten maken van methodes uit de statistische besluitvorming wat in latere hoofdstukken aan bod komt.</p>
<p>De cursus is als volgt georganiseerd: In hoofdstuk <a href="chap-design.html#chap:design">3</a> verdiepen we ons in studiedesign. Vervolgens gaan we in op data-exploratie in hoofdstuk <a href="chap-describe.html#chap:describe">4</a>, hierbij zullen we de gegevens in een steekproef grondig exploreren zodoende inzicht te verwerven in de data en hoe we ze statistisch kunnen modelleren. In hoofdstuk <a href="chap-besluit.html#chap:besluit">5</a> introduceren we de grondslagen van statistische besluitvorming die het ons mogelijk maakt om effecten die we observeren in de steekproef te kunnen veralgemenen naar de populatie toe. In hoofdstukken <a href="chap-linReg.html#chap:linReg">6</a>-<a href="chap-glm.html#chap:glm">10</a> zullen we meer geavanceerde statistische modellen en methoden introduceren om data te modelleren en voor statistische besluitvorming.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="4">
<li id="fn4"><p>B.v. omdat het ook toekomstige subjecten omvat<a href="belangrijke-concepten-conventies.html#fnref4">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inleiding.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-design.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/02-Concepten.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Statistiek_2019_2020.pdf", "Statistiek_2019_2020.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
